#!/usr/bin/perl
use strict;
use Switch;

# Llibreries 
use CGI qw(:standard);
use CGI::Carp qw(warningsToBrowser fatalsToBrowser);

#Constants
use constant PASSWORD => "1234";
use constant USER => "periberni";

# Funcions
sub print_order{

print "<TITLE>Llistar Lloguers</TITLE>\n";
print "<H1>Comprovant del Lloguer</H1>\n";


print "<table>\n";
print "<tr><td><b>Model del Vehicle:</b></td>\n";
print "<td>$_[0]</td></tr>\n";
print "<tr><td><b>Tipus de motor:</b></td>\n";
print "<td>$_[1]</td>\n";
print "</tr>\n";
print "<tr><td><b>Dies del lloguer:</b></td>\n";
print "<td>$_[2]</td></tr>\n";
print "<tr><td><b>Quantitat de vehicles:</b></td>\n";
print "<td>$_[3]</td></tr>\n";
print "<tr><td><b>Descompte(%):</b></td>\n";
print "<td>$_[4]</td></tr>\n";
print "</table>\n";
print "<HR>\n";
print "<b>Import total:</b> $_[5] euros.\n";


}


print "Content-type: text/html\n\n";

if (param())
{
	my $pass = param('password');
	my $user = param('userid');
	my @camps;

	if (($pass eq PASSWORD) && ($user eq USER)) 
	{
		print "<title>Llistar Lloguers</title>";
		print "<h1>Llista lloguers</h1>";
		print "<table border='1' style='border-collapse:collapse; text-align:center;'><tr><td><b>Model de Vehicle</b></td><td><b>Tipus de motor</b></td><td><b>Dies del lloguer</b></td><td><b>Quantitat</b></td><td><b>Descompte</b></td><td><b>Import total</b></td></tr>";
		
		my $fitxer="$ENV{'DOCUMENT_ROOT'}/lloguers.txt";
		if (-e $fitxer)
		{
		    open (FILEHANDLE, "<$ENV{'DOCUMENT_ROOT'}/lloguers.txt") or die $!;
		    while (my $line = <FILEHANDLE>) 
		    {
			@camps = split(/:/, $line);
			print "<tr><td>$camps[0]</td><td>$camps[1]</td><td>$camps[2]</td><td>$camps[3]</td><td>$camps[4]</td><td>$camps[5]</td>";
		    }
		}
		print "</table>";
		print "<br /><br /><a href='http://localhost/main.html'>Tornar a la plana principal</a>\n";
			

	} else 
	{
		print "<TITLE>Llistar lloguers: Error</TITLE>";
		print "Si us plau, introdueix un userid i password correctes\n";
		print "<br /><br /><a href='http://localhost/main.html'>Tornar a la plana principal</a>\n";
	}
		
	close FILEHANDLE;

}




